# Generated by Django 3.0.8 on 2020-07-31 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmallSemesterChild', '0002_userextension'),
    ]

    operations = [
        migrations.AddField(
            model_name='userextension',
            name='hassendemail',
            field=models.IntegerField(default=0),
        ),
    ]
