# Generated by Django 3.1 on 2020-08-12 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmallSemesterChild', '0002_belong_browse_comment_demo_document_favorite_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='doc_creater',
            field=models.TextField(null=True),
        ),
    ]
