# Generated by Django 3.0.8 on 2020-08-01 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmallSemesterChild', '0003_userextension_hassendemail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(blank=True, null=True)),
                ('phonenumber', models.CharField(blank=True, max_length=20000, null=True)),
            ],
        ),
    ]
