# Generated by Django 3.1 on 2020-08-10 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmallSemesterChild', '0004_test3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plain',
            name='plainname',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='test3',
            name='phonenumber',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
